name: Approve Security PRs

on: pull_request 

permissions: 
  contents: write 

jobs:
  approve: 
    runs-on: ubuntu-latest 
    if: contains(github.event.pull_request.title, 'security')
    steps: 
      - run: | 
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
          -d '{"commit_title":"Approved","commit_message":"Approved by security bot"}' 
